name = "Harmonyubuntu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fbb6be85d527f7cbd6b692e35c7058d485bd6637e2b3e445997a6cd03487544"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
