name = "Harmonyubuntu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f066a637de9b36cc0a30a5eca31142d88a627df7dfe3b166cd6e36a4bdeb6fc"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
