name = "Harmonyubuntu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e933ceb11a8655d0c0fa8e77af367a9ec8561715150a9fee2cfdf397d639dec7"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
