name = "Harmonyubuntu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61d69bd45309a7ae24b820b8bcb63f2a84990c5fe3311860ba424fb30086ca03"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
