name = "Harmonyubuntu"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "216e9bc57079fc7f48d568f4bf1b092cc57b9937cb1d733b8062d89794d37681"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
