name = "harmonyubuntu"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "134d832bbd6fb6b872bfc20bf214af79c08f6c94b166c923fbc49887bfa8e4ca"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
