name = "Harmonyubuntu"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df1248c8ea1fa694661de5a71173a8a5f2c29250a9ede6bcbdbdb9a97f0294c"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
