name = "Harmonyubuntu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c8da2db00f7a30ead86002144f3222edaacbc3e9b6c45fecb509eb57785bcc"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
