name = "Harmonyubuntu"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3104b4da464741da4dccb7d12e14ed02d3b56731b33edceb11e5b8b943417a6"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
